name: points_verts
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.1+44

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  background_fetch: ^1.0.0
  cached_network_image: ^3.0.0-nullsafety
  collection: ^1.15.0-nullsafety.4
  csv: ^5.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0-nullsafety.1
  flutter_dotenv: ^5.0.0
  flutter_local_notifications: ^9.2.0
  flutter_native_splash: ^2.0.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  geolocator: ^8.1.1
  google_maps_flutter: ^2.0.11
  http: ^0.13.0
  intl: ^0.17.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.0
  sqflite: ^2.0.0
  url_launcher: ^6.0.0
  weather_icons: ^3.0.0-nullsafety.0
  google_polyline_algorithm: ^3.1.0
  add_2_calendar: ^2.1.3
  carousel_slider: ^4.0.0
  package_info_plus: ^1.4.2
  timezone: ^0.8.0
  xml: ^5.4.0
  latlong2: ^0.8.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - .env
    - assets/walk_data.json
    - assets/light/
    - assets/dark/
    - assets/raw/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
