name: points_verts
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_cache_registry:
    path: packages/app_cache_registry
  app_user_preferences_registry:
    path: packages/app_user_preferences_registry
  bloc: ^8.1.4
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  maps_api:
    path: packages/maps_api
  maps_repository:
    path: packages/maps_repository
  path_provider: ^2.1.5
  points_verts_repository:
    path: packages/points_verts_repository
  shared_preferences: ^2.3.3
  weather_api:
    path: packages/weather_api

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
