name: trail_parser_api
description: A dart api which fetches and parses trail files
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  equatable: ^2.0.5
  http: ^1.2.2
  json_map_typedef:
    path: ../json_map_typedef
  maps_api:
    path: ../maps_api
  path: ^1.9.0
  xml: ^6.5.0
