name: odwb_points_verts_api
description: An API that provides access to Open Source ODWB Points Verts data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  json_map_typedef:
    path: ../json_map_typedef

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - ../../assets/walk_data.json
