name: app_cache_registry
description: A registry for all the caches used in the application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cache_manager:
    path: ../cache_manager
  jsonable:
    path: ../jsonable
  maps_api:
    path: ../maps_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
