name: app_cache_registry
description: A registry for all the caches used in the application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  adeps_website_api:
    path: ../adeps_website_api
  intl: ^0.19.0
  json_map_typedef:
    path: ../json_map_typedef
  maps_api:
    path: ../maps_api
  meta: ^1.15.0
  odwb_points_verts_api:
    path: ../odwb_points_verts_api
  persistent_storage_manager:
    path: ../persistent_storage_manager
  service_registry:
    path: ../service_registry
  trail_parser_api:
    path: ../trail_parser_api
  weather_api:
    path: ../weather_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
