// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVjm4H0-JCNuwMg5EILd6nqbUtINyHVA',
    appId: '1:1002305900075:android:b3f38eb30d5ec7dc6fa46e',
    messagingSenderId: '1002305900075',
    projectId: 'points-verts-328310',
    storageBucket: 'points-verts-328310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkNO9OUfW9pO8WAGRynn7qNYUNk_ItysM',
    appId: '1:1002305900075:ios:be3012677402a8506fa46e',
    messagingSenderId: '1002305900075',
    projectId: 'points-verts-328310',
    storageBucket: 'points-verts-328310.appspot.com',
    iosClientId: '1002305900075-9ur2idsnunh35i9gtnd2a8h950gv0vlf.apps.googleusercontent.com',
    iosBundleId: 'dev.alpagaga.pointsverts',
  );
}
