name: walks_repository
description: A dart repository to fetch, manipulate and store the walks data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  adeps_website:
    path: ../adeps_website
  odwb_points_verts_api:
    path: ../odwb_points_verts_api
