name: weather_api
description: The interface for an API that provides access to weather-related services
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  json_map_typedef:
    path: ../json_map_typedef
  maps_api:
    path: ../maps_api
  open_weather_api:
    path: ../open_weather_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
